name: nightly
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: publish-nightly
jobs:
  checks:
    runs-on: ubuntu-latest
    name: check for recent changes
    outputs:
      no_changes: ${{ steps.has_changes.outputs.no_changes }}
    steps:
    - uses: actions/checkout@v2
    - name: print latest_commit
      run: echo ${{ github.sha }}
    - id: has_changes
      continue-on-error: true
      name: check for recent changes
      # TODO: Disable this once testing is completed.
      # if: ${{ github.event_name == 'schedule' }}
      run: (test $(git rev-list ${{ github.sha }} --after="24 hours" --count -- ':(exclude).github/' ':(exclude).vscode/') -ne 0) && (echo "::set-output name=no_changes::true")
  windows:
    runs-on: windows-latest
    needs: checks
    if: ${{ needs.checks.outputs.no_changes != 'true' }}
    steps:
    - uses: actions/checkout@v2
    - name: use node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: configure nightly
      run: yarn run configure-nightly
    - name: run tests
      run: yarn run test
    - name: make package
      run: yarn run make
    - name: upload windows build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts-windows
        path: |
          packages/obs-remote/out/make/
          !packages/obs-remote/out/make/**/*.nupkg
        if-no-files-found: error
  linux:
    runs-on: ubuntu-latest
    needs: checks
    if: ${{ needs.checks.outputs.no_changes != 'true' }}
    steps:
    - uses: actions/checkout@v2
    - name: use node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: configure nightly
      run: yarn run configure-nightly
    - name: run tests
      run: yarn run test
    - name: make package
      run: yarn run make
    - name: upload linux build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts-linux
        path: packages/obs-remote/out/make/
        if-no-files-found: error
  macos:
    runs-on: macos-latest
    needs: checks
    if: ${{ needs.checks.outputs.no_changes != 'true' }}
    steps:
    - uses: actions/checkout@v2
    - name: use node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: configure nightly
      run: yarn run configure-nightly
    - name: run tests
      run: yarn run test
    - name: make package
      run: yarn run make
    - name: upload macos build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts-macos
        path: packages/obs-remote/out/make/
        if-no-files-found: error
  publish-nightly:
    runs-on: ubuntu-latest
    needs:
      - windows
      - linux
      - macos
      - checks
    if: ${{ needs.checks.outputs.no_changes != 'true' }}
    steps:
    - name: download build artifacts
      uses: actions/download-artifact@v2
    - name: deploy nightly
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: nightly
        prerelease: true
        title: nightly
        files: |
          artifacts-windows/**/*
          artifacts-linux/**/*
          artifacts-macos/**/*
