name: nightly
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: publish-nightly
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: configure nightly
      run: yarn run configure-nightly
    - name: run tests
      run: yarn run test
    - name: make package
      run: yarn run make
    - name: upload windows build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts-windows
        path: |
          packages/obs-remote/out/make/
          !packages/obs-remote/out/make/**/*.nupkg
        if-no-files-found: error
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: configure nightly
      run: yarn run configure-nightly
    - name: run tests
      run: yarn run test
    - name: make package
      run: yarn run make
    - name: upload linux build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts-linux
        path: packages/obs-remote/out/make/
        if-no-files-found: error
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: configure nightly
      run: yarn run configure-nightly
    - name: run tests
      run: yarn run test
    - name: make package
      run: yarn run make
    - name: upload macos build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts-macos
        path: packages/obs-remote/out/make/
        if-no-files-found: error
  publish-nightly:
    runs-on: ubuntu-latest
    needs:
      - windows
      - linux
      - macos
    steps:
    - name: download build artifacts
      uses: actions/download-artifact@v2
    - name: deploy nightly
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: nightly
        prerelease: true
        title: nightly
        files: |
          artifacts-windows/**/*
          artifacts-linux/**/*
          artifacts-macos/**/*
